// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace N_TierSolutionGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "N_TierSolutionGenerator.9ceba233-75d2-45d3-ac59-f22254ba4d72";
        public const string Name = "N_TierSolutionGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
