// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace N_TierSolutionGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string N_TierSolutionGeneratorString = "f79c6f22-a7e3-4ce1-8fe5-9949d89cbc11";
        public static Guid N_TierSolutionGenerator = new Guid(N_TierSolutionGeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ItemNodeGroup = 0x0002;
        public const int MyCommand = 0x0100;
        public const int GenerateLayersCommand = 0x0200;
    }
}